### ISSUE TITLE
Printing lists of maps

### ISSUE THREAD

**Issue by swapnens** [Ferdzzzzzzzz/pretty_json#2]
Your printPrettyJson takes only dynamic maps.
You should also support jsons where the external object is a list.

**Comment by fsteenkamp** [comment]
Sorry for the late reply, I'll look into it this weekend 👍

**Comment by fsteenkamp** [comment]
I see you created a pull request @swapnens, will review and get back to you tomorrow

**Comment by fsteenkamp** [comment]
@swapnens merged and deployed your change, hope the delay didn't cause any problems 😄
